import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {spawn} from 'node:child_process';
import {createRequire} from 'node:module';
const require=createRequire(process.env.YANG_BROWSER_RUNTIME ? path.resolve(process.env.YANG_BROWSER_RUNTIME,'package.json') : import.meta.url);
const {chromium}=require('playwright');
const root=path.resolve(import.meta.dirname,'..');
const server=spawn(process.env.PYTHON || 'python',['-u',path.join(root,'tests/browser_server.py')],{cwd:root,windowsHide:true,stdio:['ignore','pipe','pipe']});
let browser;
const checks=[],errors=[];
const record=name=>{checks.push(name);process.stdout.write(name+'\n');};
try{
  const url=await new Promise((resolve,reject)=>{
    let buffer='';const timer=setTimeout(()=>reject(new Error('fixture startup timeout')),10000);
    server.stdout.on('data',chunk=>{buffer+=chunk;const first=buffer.split('\n')[0];try{const value=JSON.parse(first);clearTimeout(timer);resolve(value.url);}catch{}});
    server.stderr.on('data',chunk=>process.stderr.write(chunk));
    server.once('exit',code=>reject(new Error('fixture exited '+code)));
  });
  browser=await chromium.launch({headless:true});
  const context=await browser.newContext({viewport:{width:1280,height:900},acceptDownloads:true});
  const page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));
  await page.goto(url,{waitUntil:'domcontentloaded'});
  await page.getByRole('button',{name:'登录自己的空间',exact:true}).waitFor();
  assert.equal(await page.evaluate(()=>SPACE),'demo');
  assert.equal(await page.getByText('OWNER_PRIVATE',{exact:true}).count(),0);
  assert.equal((await context.request.get(url+'/api/state')).status(),401);
  await page.locator('#fab').click();await page.locator('#v-new textarea').fill('DEMO_ONLY_DRAFT');
  await page.getByRole('button',{name:'放进念头堆',exact:true}).click();
  record('public health does not unlock private APIs; demo draft stays local');
  await page.getByRole('button',{name:'登录自己的空间',exact:true}).click();
  await page.getByLabel('访问口令',{exact:true}).fill('incorrect');await page.getByRole('button',{name:'登录',exact:true}).click();
  await page.getByRole('alert').filter({hasText:'认证失败'}).waitFor();
  await page.getByLabel('访问口令',{exact:true}).fill('BROWSER_SYNTHETIC_TOKEN_0123456789abcdef');
  await page.getByRole('button',{name:'登录',exact:true}).click();
  await page.waitForFunction(()=>SPACE==='private' && !!SYNC.base && !SYNC.dirty && !SYNC.running);
  assert.equal(await page.evaluate(()=>S.sparks.some(s=>s.text==='DEMO_ONLY_DRAFT')),false);
  assert.ok((await context.cookies()).some(c=>c.httpOnly));
  assert.equal(await page.evaluate(()=>JSON.stringify(localStorage).includes('SYNTHETIC_KEY_ONLY')),false);
  record('login failure recovery, HttpOnly session and demo/private isolation');
  await page.locator('#fab').click();await page.locator('#v-new textarea').fill('浏览器完整流程念头');
  await page.getByRole('button',{name:'直接开始养',exact:true}).click();
  await page.locator('#v-one .title').filter({hasText:'浏览器验收想法'}).waitFor();
  await page.getByRole('button',{name:'追问我',exact:false}).click();
  await page.locator('.prompt textarea').waitFor();await page.locator('.prompt textarea').fill('第一位用户是下雨回家的邻居。');
  await page.getByRole('button',{name:'记下来',exact:true}).click();
  await page.waitForFunction(()=>!SYNC.dirty && !SYNC.running);
  record('idea capture, model shaping, real SSE UI and growth record save');
  await page.getByRole('button',{name:'追问我',exact:false}).click();
  await page.getByRole('button',{name:'算了',exact:true}).click();
  assert.equal(await page.locator('.prompt').count(),0);
  record('stream cancellation clears the pending prompt');
  await page.getByRole('button',{name:'分叉',exact:false}).click();
  await page.getByRole('button',{name:'分一个空的',exact:true}).click();
  await page.waitForFunction(()=>!SYNC.dirty && !SYNC.running);
  record('fork creates and persists a separate idea');
  await page.getByRole('button',{name:'这个先凉着吧',exact:true}).click();
  await page.locator('#whyta').fill('验证归档删除同步。');
  await page.getByRole('button',{name:'放进「凉了的」',exact:true}).click();
  await page.waitForFunction(()=>!SYNC.dirty && !SYNC.running);
  assert.ok(await page.evaluate(()=>S.cold.some(x=>x.why==='验证归档删除同步。')));
  record('archive removes live idea and syncs the reason');
  // Hold the first sync response while another local edit occurs.
  let release,started;const held=new Promise(r=>release=r),seen=new Promise(r=>started=r);let once=true;
  await page.route('**/api/sync',async route=>{if(once){once=false;started();await held;}await route.continue();});
  await page.evaluate(()=>{S.sparks.push({id:'during-a',text:'first edit',at:Date.now()});save();});await seen;
  await page.evaluate(()=>{S.sparks.push({id:'during-b',text:'second edit',at:Date.now()});save();});release();
  await page.waitForFunction(()=>!SYNC.dirty && !SYNC.running);await page.unroute('**/api/sync');
  let remote=await (await context.request.get(url+'/api/state')).json();assert.ok(remote.sparks.some(x=>x.id==='during-a') && remote.sparks.some(x=>x.id==='during-b'));
  record('edits made during an in-flight save are delivered in the next revision');
  const changed={...remote.sparks.find(x=>x.id==='during-a'),text:'REMOTE_CONFLICT'};
  assert.equal((await context.request.post(url+'/api/sync',{data:{base_revision:remote.revision,changes:{sparks:{upsert:[changed]}}}})).status(),200);
  await page.evaluate(()=>{S.sparks.find(x=>x.id==='during-a').text='LOCAL_CONFLICT';save();});
  await page.getByRole('button',{name:'冲突项保留本机版本',exact:true}).waitFor();
  await page.getByRole('button',{name:'冲突项保留本机版本',exact:true}).click();
  await page.waitForFunction(()=>!SYNC.dirty && !SYNC.running && !SYNC.conflict);
  remote=await (await context.request.get(url+'/api/state')).json();assert.equal(remote.sparks.find(x=>x.id==='during-a').text,'LOCAL_CONFLICT');
  record('stale revisions surface explicit conflict resolution without losing local edits');
  await context.setOffline(true);
  await page.evaluate(()=>{S.sparks.push({id:'offline-draft',text:'OFFLINE_DRAFT',at:Date.now()});save();});
  await page.waitForFunction(()=>!!SYNC.error);
  assert.ok(await page.evaluate(()=>JSON.parse(localStorage.getItem(LS)).sparks.some(x=>x.id==='offline-draft')));
  await context.setOffline(false);await page.waitForFunction(()=>!SYNC.dirty && !SYNC.running,{},{timeout:15000});
  record('offline edits survive and retry after reconnection');
  await page.getByRole('button',{name:'数据',exact:true}).click();
  const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'导出',exact:true}).click();
  const download=await downloadPromise;assert.ok(download.suggestedFilename().endsWith('.jsonl.txt'));
  const file=await download.path();
  await page.locator('input[type=file]').setInputFiles(file);
  await page.getByRole('button',{name:'确认导入',exact:true}).click();
  await page.waitForFunction(()=>!SYNC.dirty && !SYNC.running);
  record('Blob download and validated JSONL import round trip');
  const destination=path.join(root,'test-results');fs.mkdirSync(destination,{recursive:true});
  await page.getByRole('button',{name:'图谱',exact:true}).click();
  await page.getByRole('button',{name:'桥',exact:true}).click();
  await page.getByRole('button',{name:'算一遍',exact:true}).click();
  await page.waitForFunction(()=>GV.bridges!==null || !!GV.err);assert.equal(await page.evaluate(()=>GV.err),'');
  await page.screenshot({path:path.join(destination,'desktop.png'),fullPage:true});
  await page.setViewportSize({width:375,height:812});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.screenshot({path:path.join(destination,'mobile.png'),fullPage:true});
  await page.setViewportSize({width:812,height:375});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.emulateMedia({reducedMotion:'reduce'});
  record('desktop, 375px mobile and landscape graph layouts without horizontal overflow');
  await page.getByRole('button',{name:'退出登录',exact:true}).click();
  await page.waitForFunction(()=>SPACE==='demo');
  assert.ok(await page.evaluate(()=>S.sparks.some(x=>x.text==='DEMO_ONLY_DRAFT')));
  assert.equal(await page.getByText('OWNER_PRIVATE',{exact:true}).count(),0);
  assert.equal((await context.request.get(url+'/api/state')).status(),401);
  record('logout returns to demo namespace and revokes browser session');
  assert.deepEqual(errors,[]);
  fs.writeFileSync(path.join(destination,'browser-validation.json'),JSON.stringify({synthetic_model_fixture:true,checks,errors,passed:true},null,2));
} finally {if(browser)await browser.close();server.kill();}
